### PR TITLE
Correct the way tox is written

### PR DESCRIPTION
**Pull request by jugmac00**
tox never gets capitalized.

### CODE REVIEW

**Comment by hroncok** [comment]
What is the source of this information? Does it not even get capitalized at the beginning of a sentence?

**Comment by jugmac00** [comment]
This is tribal knowledge :-)

And certainly our own documentation is a good source for how to write it:

version 3
https://tox.wiki/en/latest/

version 4
https://tox.wiki/en/rewrite/

And basically all presentations we did:

Bernát
https://www.youtube.com/watch?v=NX166Jk8T3w
https://www.youtube.com/watch?v=IiRBwpyqlho
https://www.youtube.com/watch?v=iHbfI4GA0pA
https://www.youtube.com/watch?v=sIlJhPzruwU
https://www.youtube.com/watch?v=sIlJhPzruwU
https://www.youtube.com/watch?v=SFqna5ilqig&t=1s

Anthony
https://www.youtube.com/watch?v=75WBE_qbpGk&t=2s

Oliver
https://www.youtube.com/watch?v=PrAyvH-tm8E&t=1s

Me
https://jugmac00.github.io/talks/

And not to forget this one :-)
https://twitter.com/jugmac00/status/1524452912684011521

So, yes, I'd really appreciate if you write tox all lowercaps, even on the beginning of sentences and in even in headlines.

Cheers,
Jürgen

P.S.: Thanks a lot for this plugin. I am thinking about introducing it at Canonical and creating a ppa to distribute it.

**Comment by hroncok** [comment]
Thanks.

**Comment by hroncok** [comment]
BTW Would you capitalize tox in a German sentence, as a noun? :D

**Pull request merged**
